-- 1. Tabela de Utilizadores
create table "public"."usuarios" (
    "id" bigint generated by default as identity not null,
    "nome" text,
    "email" text,
    "senha" text,
    "cpf" text,
    "endereco" text,
    "cep" text,
    "telefone" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."usuarios" add constraint "usuarios_pkey" primary key ("id");

-- 2. Tabela de Consultas (com a coluna hora incluída)
create table "public"."consultas" (
    "id" bigint generated by default as identity not null,
    "email_usuario" text,
    "local_clinica" text,
    "endereco" text,
    "telefone" text,
    "doutor" text,
    "data" text,
    "hora" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."consultas" add constraint "consultas_pkey" primary key ("id");

-- 3. Tabela de Medicamentos (com a coluna hora incluída)
create table "public"."medicamentos" (
    "id" bigint generated by default as identity not null,
    "email_usuario" text,
    "nome_medicamento" text,
    "nome_usuario" text,
    "data" text,
    "hora" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."medicamentos" add constraint "medicamentos_pkey" primary key ("id");

-- 4. View do Histórico (Junta consultas e medicamentos)
create or replace view "public"."vw_historico" as  
  SELECT id::text AS id, data, doutor AS titulo, local_clinica AS descricao, 'consulta'::text AS tipo 
  FROM public.consultas
  UNION ALL
  SELECT id::text AS id, data, nome_medicamento AS titulo, nome_usuario AS descricao, 'medicamento'::text AS tipo 
  FROM public.medicamentos;